## realtime processing project

generated a syntetic ecommerce csv with some junk in it.

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('../input/ecommerce_orders.csv')

In [4]:
print(df.head())
print(df.shape)
print(df.dtypes)
print(df.isnull().sum())
print(df.describe())
print(df.duplicated().sum())

   order_id customer_id  order_date  product_name        category  quantity  \
0  ORD00073    CUST1119         NaN       T-Shirt        Clothing         5
1  ORD00025    CUST1113  2024-02-08     Desk Lamp  Home & Kitchen         2
2  ORD00052    CUST1172  2024-04-30      Notebook      Stationery         3
3  ORD00171    CUST1041  2024-08-02      Yoga Mat          Sports         3
4  ORD00099    CUST1181  2024-05-02  Dumbbell Set          Sports         1

   unit_price  discount  total_amount payment_method  country     status  \
0       21.22      0.11         94.43         PayPal    Italy  Delivered
1       33.44      0.05         63.54    Credit Card  Belgium  Delivered
2        9.18      0.19         22.31         PayPal       UK    Shipped
3       42.21      0.10        113.97         PayPal   France  Delivered
4      108.68      0.13         94.55     Debit Card  Germany  Delivered

   customer_rating
0              3.4
1              3.6
2              1.8
3              1.6
4              1.1
(210, 13)
order_id               str
customer_id            str
order_date             str
product_name           str
category               str
quantity             int64
unit_price         float64
discount           float64
total_amount       float64
payment_method         str
country                str
status                 str
customer_rating    float64
dtype: object
order_id           0
customer_id        8
order_date         6
product_name       3
category           0
quantity           0
unit_price         0
discount           0
total_amount       5
payment_method     0
country            0
status             0
customer_rating    0
dtype: int64
         quantity  unit_price    discount  total_amount  customer_rating
count  210.000000  210.000000  210.000000    205.000000       210.000000
mean     2.985714  116.416190    0.118048    328.036976         3.012381
std      1.635370  216.799157    0.185742    691.254797         1.220494
min     -5.000000 -967.860000   -0.100000  -3757.880000        -1.000000
25%      2.000000   39.690000    0.050000     86.410000         2.100000
50%      3.000000   57.495000    0.100000    168.020000         3.000000
75%      4.750000  104.362500    0.147500    305.330000         3.800000
max      5.000000  976.590000    2.000000   4345.830000         7.500000
7

In [11]:
df['category'].unique()

<ArrowStringArray>
[      'Clothing', 'Home & Kitchen',     'Stationery',         'Sports',
    'Electronics',    'Accessories']
Length: 6, dtype: str

In [5]:
df[df['order_date'] > '2027-01-01']

,order_id,customer_id,order_date,product_name,category,quantity,unit_price,discount,total_amount,payment_method,country,status,customer_rating
18,ORD00054,CUST1001,2027-06-30,Air Fryer,Home & Kitchen,4,97.98,0.03,380.16,PayPal,Netherlands,Cancelled,1.9
109,ORD00197,CUST1006,2035-12-01,Mechanical Keyboard,Electronics,2,137.58,0.05,261.40,Credit Card,Spain,Delivered,2.5
156,ORD00167,CUST1019,2030-01-15,Coffee Maker,Home & Kitchen,4,75.06,0.20,240.19,PayPal,UK,Shipped,1.4

In [14]:
df['payment_method'].unique()
df[df['status'] == 'Refunded']

,order_id,customer_id,order_date,product_name,category,quantity,unit_price,discount,total_amount,payment_method,country,status,customer_rating
203,ORD00198,CUST1101,2024-06-07,Backpack,Accessories,2,56.22,0.02,110.19,Credit Card,Belgium,Refunded,4.1

## validations same as part 1 lets seeeeee
if optional is missing flag . if mandatory missing drop


- *order_id* mandatory must be 8 char long format like (e.g. ORD00042)
- *customer_id* mandatory must be 8 char long format like (e.g. CUST1042)
- *order_data* mandatory range hmmm cant be before 2020-01-01 and cant be after 2026-12-31
- *product_name*  mandatory -> drops if missing
- *category* not mandatory if present cant exceed 50 char flag if so 
- *quantity* mandatory cant be negaive or 0
- *unit_price* mandatory cant be negative if 0 flag
- *discount* has to be in rang of 0-1 represtnt 0%-100%
- *total_amount* mandatory cant be negative or 0
- *payment_methode* mandatory needs later unification type shi Credit Card, PayPal, Debit Card, Bank Transfer
- *Country* flag no present 
- *status* mandatory Delivered, Shipped, Processing
- *customer_rating* if present range 1-5

niet zo perfect zal meer indetail terwijl ik de valiator maak